###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Aahmed",
    "lastName": "Abuari",
    "email": "buhari@gmail.com",
    "password":"aa123"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    
    "email": "buhari@gmail.com",
    "password":"aa123"
}


###
GET http://localhost:3000/user/24b619ec-e659-41f4-b82a-f9455cb16482

###
GET   http://localhost:3000/user

###
DELETE  http://localhost:3000/user/9d28308d-046c-45f5-b437-44dfd3cc6635

###
PATCH   http://localhost:3000/user/56ee6bea-14af-4942-a6bf-d7ac0cb45d2b
Content-Type: application/json

{
    "firstName":"buhari ii",
    "lastName":"buhari updar"
}

